### ISSUE TITLE
Add interactive map

### ISSUE THREAD

**Issue by eyvorchuk** [pacificclimate/osprey-flask-app#16]
In a Jupyter notebook, an interactive map using the `ipyleaflet` package should be used to allow a user to select the `lon/lat` pour points by clicking on a point in the map, which will be used as input to the flask app. This functionality will eventually be used by the streamflow portal.

**Comment by adasungar** [comment]
https://github.com/pacificclimate/osprey-flask-app/tree/i7-progress-bar
